grammarexpert/exam/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from django.conf.urls import url
from django.urls.base import reverse_lazy


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.update_profile, name='profile'),
    path('activate/<str:uidb64>/<str:token>', views.activate, name='activate'),
    path('attempt/<str:code>', views.attempt, name='attempt'),
    path('questionmanager',views.questionmanager,name='questionmanager'),
    path('questionmanager/del/<int:qid>',views.delete_question, name = 'delete'),
    path('',views.main_view,name='homepage'),
    path('practice/',views.practice,name='practice'),
    path('fetch/',views.fetch_results,name='fetch_results'),
    path('getresult/',views.get_results,name='get_results'),
    path('updatecomment/',views.update_comment,name='update_comment'),
    path('getuserperformance/',views.getuserperformance,name='getuserperformance'),
    path('leaderboard/<int:qid>',views.leaderboard, name = 'leaderboard'),
    path('getuserattemptdata/', views.getuserattemptdata, name='getuserattemptdata'),
    path('analytics/', views.getallusersummary, name='analytics'),
    path('getuserperfdata/<int:uid>',views.getuserperfdata, name = 'getuserperfdata'),
    path('canattempt/<str:code>',views.canattempt, name = 'canattempt'),
    path('deleteattempt/<int:attemptid>',views.deleteattempt, name = 'deleteattempt'),
    path('updatequestion/<int:pk>',views.EditQuestion.as_view(), name = 'updatequestion'),
    path('reset-password/', PasswordResetView.as_view(template_name= 'registration/reset_password.html', success_url= 'done/', email_template_name= 'registration/reset_password_email.html'), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name= 'registration/reset_password_done.html'), name='password_reset_done'), # name as "password_reset_done" because the default 'reset password' view is defined to redirect to view with that name 
    # path('reset-password/confirm/<str:uidb64>/<str:token>/', PasswordResetConfirmView.as_view(template_name= 'registration/reset_password_confirm.html', success_url= 'complete/'), name='password_reset_confirm'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name= 'registration/reset_password_confirm.html', success_url= reverse_lazy('password_reset_complete')), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name= 'registration/reset_password_complete.html'), name='password_reset_complete')
]

grammarexpert/exam/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    BRANCH_CHOICES = (
        ('CSE', 'Computer Science and Engineering'),
        ('ECE', 'Electronics and Communication'),
        ('EEE', 'Electrical and Electronics Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CE', 'Civil Engineering'),
        ('CHE', 'Chemical Engineering'),
        ('IT', 'Information Technology'),
        ('PHM', 'Pharmacy')
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    college = models.CharField(max_length=250, blank=False)
    college_id = models.CharField(max_length=20, blank=False)
    branch_of_study = models.CharField(max_length=3, blank=False, choices=BRANCH_CHOICES)
    name = models.CharField(max_length=100, blank=False)
    class Meta:
        permissions = (
            ("create_test", "Can create tests"),
        )


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
    

class Question(models.Model):
    QUESTION_TYPES = (
        ('ES', 'Essay'),
        ('PS', 'Picture Story'),
        ('CP', 'Connect the phrases'),
        ('UW', 'Use words')
    )
    question = models.CharField(max_length = 500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length = 8,unique = True)
    word_limit = models.IntegerField(default=300)
    min_word_count = models.IntegerField(default=150)
    max_word_count_penalty = models.IntegerField(default=3)
    max_word_length_penalty = models.IntegerField(default=2)
    desired_mean_word_length = models.IntegerField(default=8)
    desired_mean_words_per_sentence = models.IntegerField(default=20)
    max_words_per_sentence_penalty = models.IntegerField(default=2)
    attempts_allowed = models.IntegerField(default=1)
    date_created = models.DateField(default=datetime.now)
    time_limit = models.IntegerField(default=30)
    question_type = models.CharField(max_length=2, blank=False, choices=QUESTION_TYPES, default='ES')
    keywords = models.TextField(default="", blank=True)
    expanded_keywords = models.TextField(default="", blank=True)
    picture = models.ImageField(default="/standard/es.jpg")
    # to add keywords, picture essay image, tags, question type (essay, picture essay, connect phrases, use words etc.)
    # would need separate checking algorithm for each

    def __str__(self):
        return "{}".format(self.question)


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    score = models.FloatField()
    Json = models.TextField()
    spellingErrors = models.IntegerField()
    grammarErrors = models.IntegerField()
    starttime = models.DateTimeField()
    endtime = models.DateTimeField()
    comments = models.CharField(max_length=255, default="")

grammarexpert/exam/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from . models import Answer,Question,Profile

 

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User 
        fields = ["username", "email", "password1", "password2"]

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("This email is already used")
        return data

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.email = self.clean_email()
        if commit:
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('name', 'college', 'college_id', 'branch_of_study')

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude=["user", "code", "date_created", "expanded_keywords"]

grammarexpert/exam/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import ListView
from django.urls import reverse_lazy
from django.db.models import Avg, Count, Max
from django.db import transaction
from django.views import generic
from . forms import UserForm, QuestionForm, ProfileForm
from . models import Question, Answer, User, Profile
from django.contrib.sites.shortcuts import get_current_site
from .tokens import account_activation_token
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
from .checker.report import Report
import json
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from datetime import datetime
from django.db.models import Avg
from django.core.mail import EmailMessage
from django.contrib.auth import login, authenticate
import random
import string
import threading
import pytz
from django.utils import timezone
import logging
import subprocess
from django.core.mail import send_mail

logger = logging.getLogger(__name__)
process = None

def startLanguageTool():
    args = ["java", "-cp", "../../LanguageTool-4.6/languagetool-server.jar", "org.languagetool.server.HTTPServer", "--port", "8082"]
    process = subprocess.Popen(args)
    logger.info("started language tool:", process.pid)

datetimeformat = "%Y %d %m %H:%M:%S %Z%z"
tz = pytz.timezone('Asia/Kolkata') #TODO: set to users timezone somehow

@login_required(login_url="login")
#@transaction.atomic
def update_profile(request):
    # if request.method == 'POST':
    #     user_form = UserForm(request.POST, instance=request.user)
    #     profile_form = ProfileForm(request.POST, instance=request.user.profile)
    #     if user_form.is_valid() and profile_form.is_valid():
    #         user_form.save()
    #         profile_form.save()
    #         messages.success(request, _('Your profile was successfully updated!'))
    #         return redirect('settings:profile')
    #     else:
    #         messages.error(request, _('Please correct the error below.'))
    # else:
    #     user_form = UserForm(instance=request.user)
    #     profile_form = ProfileForm(instance=request.user.profile)
    # return render(request, 'registration/profile.html', {
    #     'user_form': user_form,
    #     'profile_form': profile_form
    # })
    return render(request, 'registration/profile.html', {
        'user': request.user,
        'profile': request.user.profile
    })

class EmailThread(threading.Thread):
    def __init__(self, subject, html_content, recipient):
        self.subject = subject
        self.recipient = recipient
        self.html_content = html_content
        threading.Thread.__init__(self)

    def run(self):
        msg = EmailMessage(self.subject, self.html_content, to=[self.recipient])
        msg.content_subtype = "html"
        try:
            msg.send()
        except e:
            print(e)

def send_html_mail(subject, html_content, recipient):
    EmailThread(subject, html_content, recipient).start()

def signup(request):
    c = Profile.objects.order_by().values_list('college').distinct()
    colleges = [col[0] for col in c if col[0]]
    print(colleges)
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            profile = profile_form.save(commit = False)
            user = user_form.save(commit = False)
            user.is_active = False
            user.save()
            user.profile.name = profile.name
            user.profile.college = profile.college
            user.profile.college_id = profile.college_id
            user.profile.branch_of_study = profile.branch_of_study
            user.save()
            
            
            current_site = get_current_site(request)
            mail_subject = 'Activate your grammar expert account.'
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            tok = account_activation_token.make_token(user)          
            message = render_to_string('registration/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': uid,
                'token': tok,
            })
            to_email = user_form.cleaned_data.get('email')

            send_html_mail(mail_subject, message, to_email)
            # email = EmailMessage(
            #             mail_subject, message, to=[to_email]
            # )
            # email.send()
            # send_mail(mail_subject, message, 'grammarexpert@vishnu.edu.in', [to_email])
            return render(request, 'registration/message.html', {'message':'Please confirm your email address to complete the registration'})
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'registration/signup.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'college_list': colleges
    })

def activate(request, uidb64, token, backend='django.contrib.auth.backends.ModelBackend'):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)

    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect('homepage')
    else:
        return render(request, 'registration/message.html', {"message":'Activation link is invalid!'})

def not_found(request, exception):
    return render(request, 'errors/not_found.html')

def server_error(request):
    return render(request, 'errors/server_error.html')

def permission_denied(request, exception):
    return render(request, 'errors/permission_denied.html')

def bad_request(request, exception):
    return render(request, 'errors/bad_request.html')

@login_required(login_url="login")
@permission_required('exam.create_test')
def questionmanager(request):
    user = request.user
    context = dict()
    if request.method == "POST":
        form = QuestionForm(request.POST,request.FILES)
        code = ''.join(random.choices(string.ascii_lowercase + string.ascii_uppercase + string.digits, k=8))
        c = Question.objects.filter(code=code)
        while len(list(c))>0:
            code = ''.join(random.choices(string.ascii_lowercase + string.ascii_uppercase + string.digits, k=8))
            c = Question.objects.filter(code=code)
        
        if form.is_valid():
            question = form.save(commit = False)
            question.user = request.user
            question.code = code

            if question.question_type!='PS':
                question.picture="/standard/"+question.question_type.lower()+".jpg"

            question.save()
            return HttpResponseRedirect("questionmanager")
        else:
            print("form is not valid",form.errors)
    else:
        form = QuestionForm()
    context['form'] = form
    context['object_list'] = Question.objects.filter(user_id=request.user.id)
    context['qtypes'] = Question.QUESTION_TYPES
    return render(request, template_name = 'examcreator/questionmanager.html', context=context)

@login_required(login_url="login")
def practice(request):
    context = dict()
    results = []
    questions = Question.objects.filter(user_id = 1)
    for q in questions:
        a = list(Answer.objects.filter(user_id=request.user.id,question_id=q.id))
        s = 0
        n = 0
        avg = 0
        for x in a:
            s += x.score
            n += 1
        if n>0:
            avg = s/n
        if len(a) < q.attempts_allowed:
            results.append((q, True, avg, n))
        else:
            
            results.append((q, False, avg, n))
    return render(request, template_name = 'examuser/practice.html', context={"questions":results, "qtypes":Question.QUESTION_TYPES})

def main_view(request):
    return render(request,template_name="homepage.html", context={"user": request.user})


@login_required(login_url="login")
def attempt(request,code):
    now_utc = datetime.now(pytz.timezone('UTC'))
    s = now_utc.strftime(datetimeformat)
    q = Question.objects.get(code=code)
    a = list(Answer.objects.filter(user_id=request.user.id,question_id=q.id))
    if len(a) < q.attempts_allowed:
        return render(request, template_name="examuser/attempt.html",context = {'question': q, 'starttime':s})
    else:
        return redirect('homepage')

def can_attempt_question(userid, qid):
    q = Question.objects.get(pk=qid)
    a = list(Answer.objects.filter(user_id=userid,question_id=qid))
    return len(a) < q.attempts_allowed

@login_required(login_url="login")
def canattempt(request, code):
    q = Question.objects.get(code=code)
    a = list(Answer.objects.filter(user_id=request.user.id,question_id=q.id))
    if len(a) < q.attempts_allowed:
        return JsonResponse({"status":"OK", "url":request.build_absolute_uri("/attempt/"+code)})
    else:
        return JsonResponse({"status":"You have already reached maximum attempt limit. Please try with diferent code or practice!"})

@login_required(login_url="login")
def get_results(request):
    if request.method == "POST":
        id = request.POST['id']
        qs =  Answer.objects.get(pk=id)
        if request.user == qs.user or request.user.has_perm('exam.create_test'):
            return HttpResponse(qs.Json)
        else:
            return JsonResponse([])
    else:
        return JsonResponse([])

@login_required(login_url="login")
def fetch_results(request):

grammarexpert/exam/templates/examcreator/editquestion.html
{% load static %}
{% load bootstrap4 %}
{% include 'header.html' %}
<style>
 .input-group-btn button {
    border-radius:0 5px 5px 0;
    height:40px;
 } 
 .qcreate {
     font-weight: bold;
 }  

 .card {
     margin-bottom:30px;
 }

 .card-header {
     cursor:pointer;
 }

 #advanced .row {
     margin-bottom: 20px;
 }

 h1 {
     padding:20px 0;
     text-align:center;
     background: #cccccc;
     margin-bottom:50px;
 }
</style>
<h1>Question Editor</h1>
<div class="container masthead text-center">
    {% include 'examcreator/questionform.html' %}
</div>
<div style="height:30px;"></div>

{% include 'footer.html' %}
</body>
</html>

grammarexpert/exam/templates/examcreator/getallusersummary.html
{% include "header.html" %}
{% load static %}
{% load bootstrap4 %}
<style>
    .userattempt {
        text-decoration: underline;
        cursor: pointer;
    }
    .userattempt:hover {
        font-weight: bold;
    }

    .topcontrol {
        background-color: #cccccc;
        padding-top:20px;
        margin-bottom: 20px;
    }

    .stats {
        margin-top:20px;
    }

    #analyticstable_wrapper {
        margin-bottom: 30px;
    }

</style>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>

<div class="masthead text-center">
    <div class="container-fluid topcontrol">
        <h2>Test Takers Performance</h2>
        <div class="row">
        <div class="col-sm-8 col-md-8" id="perfChartContainer">
        </div>
        <div class="col-sm-4 col-md-4">
            <form action="/analytics/" role="form" method="POST">
                {% csrf_token %}
                <p>Filter score by range</p>
                <div class= "form-inline justify-content-center">
                    
                    <label for="minscore" class="mr-sm-2" >from</label>
                    <input type="number" step="1" min="0" max="{{attrs.maxscore}}" value="{{attrs.minscore}}" id="minscore" name="minscore" class="form-control  mr-sm-2"/>
                    <label for="maxscore" class="mr-sm-2">to</label>
                    <input type="number" step="1" min="{{attrs.minscore}}" max="10" value="{{attrs.maxscore}}" id="maxscore" name="maxscore" class="form-control mr-sm-2"/>
                </div>
                <p style="margin-top:20px;">Filter by Question type</p>
                <div class= "form-inline justify-content-center">
                    <select class="form-control" name="qtype">
                        <option value="ALL">All Types</option>
                        {% for q in qtypes %}
                        {% if q.0 == chosen %}
                        <option value="{{q.0}}" selected="selected">{{q.1}}</option>
                        {% else %}
                        <option value="{{q.0}}">{{q.1}}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary" style="margin-top:20px;">Submit</button>
                <!--TODO: filter by branch etc.-->
            </form>
            <p class="stats">Total Test Takers: <span id="takercount">--</span></p>
        </div>
    </div>
</div>
<div class="container">
   
<table id="analyticstable" class="table table-responsive-sm table-responsive-md">
    <thead>
      <tr>
        <th>User</th>
        <th>Name</th>
        <th>Rank</th>
        <th>Branch</th>
        <th>Average Score</th>
        <th>Total Attempts</th>
        <th>Last Attempt Time</th>
      </tr>
    </thead>
    <tbody>
      {% for result in results %}
      <tr>
        <td class="userattempt" onclick = "showUserChart('{{result.userid}}', '{{result.username}}')">{{result.username}}</td>
        <td>{{result.profile.name}}</td>
        <td>{{ forloop.counter }}</td>
        <td>{{result.profile.branch_of_study}}</td>
        <td>{{result.avgscore}}</td>
        <td>{{result.count}}</td>
        <td>{{result.lastattempted}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>       
</div>
    <div class="modal fade" id="modChart" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                        <h4 class="modal-title" id="username"></h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    
                </div>
                <div class="modal-body">
                    <canvas id="canvas" width="568" height="300"></canvas>
                </div>
            </div>
        </div>
    </div>
    </div>
    {% include "footer.html" %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
    <script>
        $(document).ready(function () {

            var getcolor = function (branch) {
                if (branch == 'CSE') return "rgba(255,0,0,0.3)";
                else if (branch == "ECE") return "rgba(0,255,0,0.3)";
                else if (branch == "CE") return "rgba(0,0,255,0.3)";
                else if (branch == "ME") return "rgba(255,150,0,0.3)";
                else if (branch == "EEE") return "rgba(0,255,150,0.3)";
                else if (branch == "IT") return "rgba(255,0,150,0.3)";
                else return "rgba(150,255,120,0.3)";
                //TODO return based on branch later
                /*var r = Math.floor((Math.random() * 256));
                var g = Math.floor((Math.random() * 256));
                var b = Math.floor((Math.random() * 256));
                return 'rgba('+r+', '+g+', '+b+', 0.5)';*/
            }
            var mytable = $('#analyticstable').DataTable({
                lengthMenu: [
                    [25, 50, 100, -1],
                    ['25', '50', '100', 'All']
                ],
                buttons: [
                    'pageLength'
                ]
            });


            var makechart = function () {
                var data = mytable.rows({ filter: 'applied' }).data();
                $('#takercount').text(data.length);
                // create chart from data here
                var chartdata = new Array(data.length);
                var colordata = new Array(data.length);
                var labels = new Array(data.length);
                for (var i = 0; i < data.length; i++) {
                    chartdata[i] = data[i][4]; //TODO: change index when more parameters come
                    colordata[i] = getcolor(data[i][3]); //TODO, should be based on the branch
                    labels[i] = data[i][0];
                }
                // sort the data by avg score
                $('#perfChartContainer').empty();
                $('#perfChartContainer').append(
                    '<canvas id="perfChart" width="400" height="200"></canvas>');
                var canvas = document.getElementById("perfChart");
                var ctx = canvas.getContext('2d');
                ctx.clearRect(0, 0, canvas.width, canvas.height);
                var perfChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: labels,
                        datasets: [{
                            data: chartdata,
                            backgroundColor: colordata
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        legend: { display: false },
                        scales: {
                            yAxes: [{
                                ticks: { min: 0, max: 10 },
                                scaleLabel: { display: true, labelString: 'score' }
                            }],
                            xAxes: [{
                                gridLines: { display: false },
                                ticks: { display: false }
                            }]
                        }
                    }
                });
            }

            makechart();
            mytable.on('order.dt', function () {
                makechart();
            });
            mytable.on('search.dt', function () {
                makechart();
            });

        });

            //make ajax call
    </script>
    <script src="{% static "js/userperfdata.js"%}"></script>
</body>
</html>

grammarexpert/exam/templates/examcreator/questionform.html
{% load bootstrap4 %}
<form role="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6">
            {%  bootstrap_field form.question_type %}
        </div>
        <div id="pic_container" class="col-md-6">
            {%  bootstrap_field form.picture %}
        </div>
    </div>
    <div class="row">

    <div class="col-md-12">
        {%  bootstrap_field form.question %}
    </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            {%  bootstrap_field form.word_limit %}
        </div>
        
        <div class="col-md-4">
            {%  bootstrap_field form.time_limit %}
        </div>
        <div class="col-md-4">
            {%  bootstrap_field form.attempts_allowed %}
        </div>
    </div>
    <div class="card mb-12 bg-light text-dark">
        <div class="card-header" role="button" data-toggle="collapse" data-target="#advanced" aria-expanded="true" aria-controls="advanced">
            Advanced Options
        </div>
        <div id="advanced" class="collapse" aria-labelledby="advanced" data-parent="#accordion">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        {% bootstrap_field form.keywords %}
                    </div>
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                {% bootstrap_field form.min_word_count %}
                            </div>
                            <div class="col-md-6">
                                {% bootstrap_field form.max_word_count_penalty %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {% bootstrap_field form.desired_mean_word_length %}
                            </div>
                            <div class="col-md-6">
                                {% bootstrap_field form.max_word_length_penalty %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                {% bootstrap_field form.desired_mean_words_per_sentence %}
                            </div>
                            <div class="col-md-6">
                                {% bootstrap_field form.max_words_per_sentence_penalty %}
                            </div>
                        </div>
                    </div>
                </div>
                <p>
                    Note: For connect phrases question, enter each phrase in keywords as a separate line
                </p>
            </div>
        </div>
    
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-default">Reset</button>
</form>

<script>
    $(function() {
        var updatequestiontype = function() {
            var e = $('#id_question_type');
            if(e.val()=='PS') {
                $('#pic_container').show();
            } else {
                $('#pic_container').hide();
                $('#id_picture').val('');
            }
            if(e.val()=='PS') {
                $('#id_question').val('Write a story based on the given picture');
            } else if(e.val()=='CP') {
                $('#id_question').val('Connect the given phrases in given order to make a story');
            } else if(e.val()=='UW') {
                $('#id_question').val('Write an essay or story using all the provided words');
            }
        }
        updatequestiontype();
        $('#id_question_type').change(function() {
            updatequestiontype();
        })
    })
</script>